sudo: false

language: php

php:
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer update --prefer-source $PREFER_LOWEST

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  #   Coverage reporting
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
